version: '3.8'

services:
  ml-bot-service:
    build:
      context: ./ml-bot
      dockerfile: Dockerfile
    container_name: ml-bot-service
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DEEPSEEK_API_KEY: sk-57c34dd3d00f475383ae6248c13bb65e
    networks:
      - ml-bot-network

#volumes:
#  postgres-data:

networks:
  ml-bot-network:
    name: ml-bot-network
    driver: bridge